name: Build & SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: kozakmikhail1
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Build lab1
        run: |
          rm -rf laboratory_work_1/build
          mkdir laboratory_work_1/build
          cmake -S laboratory_work_1 -B laboratory_work_1/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_1/build_wrapper cmake --build laboratory_work_1/build --config Release

      # - name: Build lab2
      #   run: |
      #     rm -rf laboratory_work_2/build
      #     mkdir laboratory_work_2/build
      #     cmake -S laboratory_work_2 -B laboratory_work_2/build 
      #     build-wrapper-linux-x86-64 --out-dir laboratory_work_2/build_wrapper cmake --build laboratory_work_2/build --config Release

      - name: Build lab3
        run: |
          rm -rf laboratory_work_3/build
          mkdir laboratory_work_3/build
          cmake -S laboratory_work_3 -B laboratory_work_3/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_3/build_wrapper cmake --build laboratory_work_3/build --config Release
      
      - name: Build lab4
        run: |
          rm -rf laboratory_work_4/build
          mkdir laboratory_work_4/build
          cmake -S laboratory_work_4 -B laboratory_work_4/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_4/build_wrapper cmake --build laboratory_work_4/build --config Release

      - name: SonarCloud scan laboratory_work_1
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_1
            -Dsonar.cfamily.compile-commands=laboratory_work_1/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true

      # - name: SonarCloud scan laboratory_work_2
      #   uses: SonarSource/sonarqube-scan-action@v4
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=kozakmikhail1_cpp_lab_2
      #       -Dsonar.organization=${{ env.SONAR_ORG }}
      #       -Dsonar.sources=laboratory_work_2
      #       -Dsonar.cfamily.compile-commands=laboratory_work_2/build_wrapper/compile_commands.json
      #       -Dsonar.coverage.exclusions=**
      #       -Dsonar.cfamily.skipCoverage=true

      - name: SonarCloud scan laboratory_work_3
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_3
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_3
            -Dsonar.cfamily.compile-commands=laboratory_work_3/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true

      - name: SonarCloud scan laboratory_work_4
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_4
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_4
            -Dsonar.cfamily.compile-commands=laboratory_work_4/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true